Repository Runbhumi/Runbhumi, pull requests merged in 2020-09, with the labels that each got.

#21 📰signup page,OTP page🚑button size similar
  assets/addPost.png
  assets/checkmail.png
  assets/signUp.png
  lib/authentication/forgotPassword.dart
  lib/authentication/loginPage.dart
  lib/authentication/otpInput.dart
  lib/authentication/secondPage.dart
  lib/authentication/signUp.dart
  lib/components/button.dart
  lib/components/dividingOr.dart
  lib/components/googleOauth.dart
  lib/components/inputBox.dart
  lib/mainApp/newPost.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: frontend

#22 📰added home page
  lib/authentication/loginPage.dart
  lib/components/googleOauth.dart
  lib/mainApp/home.dart
Labels: frontend

#23 ✨ added bottom navbar and bubble tab bar
  lib/main.dart
  lib/mainApp/home.dart
  pubspec.lock
  pubspec.yaml
Labels: design, frontend

#38 🩹 Gauth Fixed 💦 Faker added
  lib/models/Events.dart
  lib/models/User.dart
  lib/services/auth.dart
  pubspec.yaml
Labels: backend

#42 ⬇ removed useless packages and started to make UI
  assets/addpostillustration.png
  lib/view/addPost.dart
  lib/view/bottomNavigation.dart
  lib/view/mainapp.dart
  lib/view/oldhome.dart
  lib/view/profilePage.dart
  lib/view/views.dart
  pubspec.lock
  pubspec.yaml
Labels: frontend

#43 Add Friend Feature Backend Added
  lib/models/Notification.dart
  lib/models/User.dart
  lib/services/NotificationService.dart
Labels: backend

#44 ✨Added Shared Prefrences, ✨added log out button, ✨made built foundation of drawer on profile page
  lib/main.dart
  lib/utils/Constants.dart
  lib/view/loginPage.dart
  lib/view/mainapp.dart
  lib/view/networkPage.dart
  lib/view/notificationsPage.dart
  lib/view/profilePage.dart
  lib/view/secondPage.dart
  lib/view/views.dart
  lib/widget/button.dart
Labels: enhancement, frontend

#45 Friend Request Logic Build Up
  lib/models/Notification.dart
  lib/services/FriendRequest.md
  lib/services/NotificationService.dart
Labels: backend

#54 📨Added Chatrooms
  lib/models/chatrooms.dart
Labels: backend
