Repository Runbhumi/Runbhumi, pull requests merged in 2020-11, with the labels that each got.

#151 🐛fixed login logout with shared prefs prob
  lib/main.dart
  lib/services/auth.dart
  lib/view/splash/splash.dart
Labels: bug

#154 ✨made UI for leave btn ✨fixed other user profile
  lib/view/profile/otherUserProfile.dart
  lib/view/profile/schedule.dart
  lib/widget/button.dart
  lib/widget/smallButton.dart
Labels: frontend

#155 🧪added a test page
  lib/main.dart
  lib/view/profile/drawer/drawer.dart
  lib/view/profile/drawer/editProfile.dart
  lib/view/profile/drawer/testPage.dart
  lib/view/views.dart
  lib/widget/button.dart
  lib/widget/googleOauth.dart
Labels: feature_request, frontend

#158 added categories in feed page and fixed some bugs
  assets/icons8-basketball-96.png
  assets/icons8-cricket-96.png
  assets/icons8-soccer-ball-96.png
  assets/icons8-volleyball-96.png
  lib/view/addPost.dart
  lib/view/home.dart
  lib/view/mainapp.dart
Labels: enhancement, frontend

#160 ✨made a basic ui of upload
  lib/services/ImageUpload.dart
  lib/view/profile/drawer/ImageCrop.dart
  lib/view/profile/drawer/editProfile.dart
  lib/view/profile/profilePage.dart
  test/widget_test.dart
Labels: frontend

#167 🏐added tabs in chats
  lib/view/Chats/messagePage.dart
  lib/view/addPost.dart
Labels: feature_request, frontend

#174 Logic for Team Invite
  lib/models/Friends.dart
  lib/models/Notification.dart
  lib/models/Teams.dart
  lib/services/NotificationService.dart
  lib/services/TeamServices.dart
  lib/view/Chats/createTeam.dart
  lib/view/Chats/inviteFriends.dart
Labels: backend, enhancement

#176 🏐added slider and max members
  lib/view/addPost.dart
  lib/view/homePage/specific_sport.dart
  lib/view/profile/drawer/drawer.dart
  lib/view/profile/otherUserProfile.dart
  lib/widget/button.dart
Labels: enhancement, frontend

#175 team's displayed and team chats added
  lib/models/Teams.dart
  lib/services/chatroomServices.dart
  lib/view/Chats/createTeam.dart
  lib/view/Chats/messagePage.dart
  lib/view/Chats/teamConversation.dart
Labels: backend, enhancement, frontend

#181 ✨changed remove friend UI & added teams page
  lib/view/mainapp.dart
  lib/view/notificationsPage.dart
  lib/view/profile/otherUserProfile.dart
  lib/view/teams/teamsList.dart
  lib/view/views.dart
  lib/widget/buildBottomNavigationBar.dart
Labels: frontend

#183 ✨fixed notification UI
  lib/view/notificationsPage.dart
Labels: bug, design, frontend

#188 added a secondary color improved UI and will be improving in future, also improved chat UI( added sent time)
  README.md
  lib/main.dart
  lib/utils/theme_config.dart
  lib/view/Chats/conversation.dart
  lib/view/Chats/messagePage.dart
  lib/view/homePage/home.dart
  lib/view/homePage/specific_sport.dart
  lib/view/notificationsPage.dart
  lib/view/profile/drawer/editProfile.dart
  lib/view/profile/profileFriendsList.dart
  lib/view/profile/profilePage.dart
  lib/view/teams/teamsPage.dart
  lib/widget/googleOauth.dart
  lib/widget/inputBox.dart
  pubspec.lock
Labels: bug, design, enhancement, feature_request, frontend

#192 Bugs Fixed And Manager Function Added
  lib/models/Teams.dart
  lib/services/TeamServices.dart
  lib/view/teams/teaminfo.dart
Labels: backend, bug

#193 improved overall ui and added type and status in add post
  lib/main.dart
  lib/utils/theme_config.dart
  lib/view/Chats/conversation.dart
  lib/view/addPost.dart
  lib/view/homePage/home.dart
  lib/view/homePage/specific_sport.dart
  lib/view/splash/splash.dart
  lib/view/teams/createTeam.dart
  lib/widget/buildTitle.dart
Labels: bug, design, enhancement, frontend

#195 completed add post frontend
  lib/utils/theme_config.dart
  lib/view/Chats/messagePage.dart
  lib/view/addPost.dart
  lib/view/homePage/home.dart
  lib/view/teams/teamsPage.dart
  lib/widget/inputBox.dart
Labels: design, enhancement, feature_request, frontend

#196 Challenge Logic
  lib/models/Notification.dart
  lib/models/Teams.dart
  lib/services/NotificationService.dart
Labels: backend, enhancement

#215 Individual event logic
  lib/models/Events.dart
  lib/services/NotificationService.dart
Labels: backend, feature_request
