Repository Runbhumi/Runbhumi, pull requests merged in 2020-10, with the labels that each got.

#58 added verifications and a adaptive dark theme
  lib/main.dart
  lib/utils/validations.dart
  lib/view/addPost.dart
  lib/view/auth/forgotPassword.dart
  lib/view/auth/loginPage.dart
  lib/view/auth/secondPage.dart
  lib/view/auth/signUp.dart
  lib/view/home.dart
  lib/view/mainapp.dart
  lib/view/moreInfo.dart
  lib/view/networkPage.dart
  lib/view/notificationsPage.dart
  lib/view/profilePage.dart
  lib/widget/inputBox.dart
  pubspec.lock
  pubspec.yaml
Labels: frontend

#60 made the build passing
  lib/view/profilePage.dart
Labels: bug

#61 ✔completed the UI of Profile Page
  lib/view/mainapp.dart
  lib/view/networkPage.dart
  lib/view/profilePage.dart
  lib/widget/drawerButton.dart
  lib/widget/widgets.dart
Labels: design, frontend

#66 made 2nd iteration of addpost page
  lib/view/addPost.dart
  lib/widget/dateTimePicker.dart
  lib/widget/widgets.dart
  pubspec.lock
  pubspec.yaml
Labels: frontend

#75 improved UI & ⛔removed teams chat for MVP
  assets/sports-illustration1.png
  lib/view/addPost.dart
  lib/view/auth/secondPage.dart
  lib/view/networkPage.dart
  lib/widget/smallButton.dart
Labels: design, frontend

#79 Friend Class Added
  lib/models/Friends.dart
  lib/models/TeamMini.dart
  lib/models/User.dart
  lib/services/auth.dart
  lib/view/addPost.dart
Labels: backend

#80 added a dialog box and improved UI
  lib/main.dart
  lib/utils/router.dart
  lib/utils/theme_config.dart
  lib/view/addPost.dart
  lib/view/editProfile.dart
  lib/view/home.dart
  lib/view/mainapp.dart
  lib/view/moreInfo.dart
  lib/view/profilePage.dart
  lib/view/splash/splash.dart
  lib/view/views.dart
  lib/widget/animations/fade_page_route.dart
  lib/widget/animations/type_write.dart
  pubspec.lock
  pubspec.yaml
Labels: frontend

#82 Added Dark Mode Switch
  lib/main.dart
  lib/utils/theme_config.dart
  lib/view/addPost.dart
  lib/view/profilePage.dart
  pubspec.lock
  pubspec.yaml
Labels: design, frontend, hacktoberfest-accepted

#83 improved UI
  lib/main.dart
  lib/utils/theme_config.dart
  lib/view/addPost.dart
  lib/view/drawer/editProfile.dart
  lib/view/drawer/moreInfo.dart
  lib/view/home.dart
  lib/view/mainapp.dart
  lib/view/networkPage.dart
  lib/view/profilePage.dart
  lib/view/splash/splash.dart
  lib/view/views.dart
  lib/widget/googleOauth.dart
  lib/widget/placeholder_widget.dart
  lib/widget/widgets.dart
Labels: frontend

#85 Minor changes and added shared preferences
  android/app/google-services.json
  documentation/Constants.md
  lib/services/EventService.dart
  lib/services/auth.dart
  lib/view/addPost.dart
  lib/view/profilePage.dart
Labels: backend

#87 🔥💪added contributors to More info
  lib/view/drawer/editProfile.dart
  lib/view/drawer/moreInfo.dart
  lib/view/home.dart
  lib/view/mainapp.dart
  lib/view/profilePage.dart
  lib/widget/contributers/contributor_detail_model.dart
  lib/widget/contributers/contributors_card_model.dart
  lib/widget/contributers/contributors_data_model.dart
  lib/widget/smallButton.dart
  lib/widget/widgets.dart
  pubspec.lock
  pubspec.yaml
Labels: design, frontend

#88 ✨UI change in profile Page & icons
  lib/view/addPost.dart
  lib/view/drawer/moreInfo.dart
  lib/view/home.dart
  lib/view/mainapp.dart
  lib/view/networkPage.dart
  lib/view/notificationsPage.dart
  lib/view/profilePage.dart
  pubspec.lock
  pubspec.yaml
Labels: design, frontend

#89 Friend View Backend Added
  documentation/editProfile.md
  lib/models/User.dart
  lib/services/EventService.dart
  lib/services/UserServices.dart
  lib/services/auth.dart
  lib/view/profilePage.dart
Labels: backend

#91 ✨added search bar and improved UI in friends list
  lib/utils/theme_config.dart
  lib/view/addPost.dart
  lib/view/profilePage.dart
  lib/widget/dateTimePicker.dart
  lib/widget/inputBox.dart
Labels: design, frontend

#94 ✨made the profile screen
  assets/add-friends.png
  assets/confirmation-illustration.png
  assets/events.png
  lib/view/addPost.dart
  lib/view/drawer/drawer.dart
  lib/view/networkPage.dart
  lib/view/profilePage.dart
  lib/view/views.dart
  lib/widget/loader.dart
  lib/widget/widgets.dart
  pubspec.lock
  pubspec.yaml
Labels: frontend

#96 Fix icon and text colour for dark mode
  lib/utils/theme_config.dart
  lib/view/home.dart
Labels: design, frontend

#102 added chatroom services
  lib/services/chatroomServices.dart
Labels: backend

#104 ✨made the UI of search result card & ✨add success noti and btn color change on reg cond
  lib/view/home.dart
  lib/view/otherUserProfile.dart
  lib/view/profilePage.dart
Labels: bug, frontend

#105 added navigation to other users profile
  assets/search-illustration.png
  lib/view/otherUserProfile.dart
  lib/view/profilePage.dart
  lib/widget/button.dart
Labels: enhancement, frontend

#107 edited Profile UI
  lib/view/drawer/editProfile.dart
Labels: frontend

#108 ✨friend request notification card UI completed
  lib/view/drawer/editProfile.dart
  lib/view/notificationsPage.dart
  pubspec.lock
  pubspec.yaml
Labels: design, frontend

#112 ✨shifted the add post to open from a floating btn
  lib/view/addPost.dart
  lib/view/mainapp.dart
Labels: frontend

#111 Direct Messages with basic functionality
  lib/services/chatroomServices.dart
  lib/view/conversation.dart
  lib/view/networkPage.dart
Labels: backend, enhancement

#115 fixed dialog problem
  lib/view/addPost.dart
Labels: bug, frontend, hacktoberfest-accepted

#119 made the UI for notifiction card
  lib/view/addPost.dart
  lib/view/networkPage.dart
  lib/view/notificationsPage.dart
  lib/view/schedule.dart
  lib/widget/smallButton.dart
Labels: design, frontend

#121 Add Friend Feature Completed
  lib/view/notificationsPage.dart
Labels: backend

#128 pictures url added to chat rooms
  lib/view/chatSchedule.dart
  lib/view/conversation.dart
  lib/view/networkPage.dart
Labels: backend

#130 made the UI oof chat screen & 🎨✨refactored
  lib/view/Chats/chatSchedule.dart
  lib/view/Chats/conversation.dart
  lib/view/Chats/messagePage.dart
  lib/view/views.dart
Labels: frontend

#140 🐛chat overlap bug solved & 🐛add post dropdown colors bug fixed
  lib/utils/theme_config.dart
  lib/view/Chats/conversation.dart
  lib/view/addPost.dart
  lib/view/splash/splash.dart
Labels: bug, frontend

#143 app made to look in MVP
  lib/view/Chats/messagePage.dart
  lib/view/drawer/drawer.dart
  lib/view/profilePage.dart
Labels: frontend
