Repository Runbhumi/Runbhumi, pull requests merged in 2020-12, with the labels that each got.

#217 made all notification card frontend
  lib/view/notificationsPage.dart
Labels: design, frontend

#218 enhanced team info ui
  lib/main.dart
  lib/view/Chats/teamConversation.dart
  lib/view/teams/teaminfo.dart
Labels: design, enhancement, frontend

#227 team info page created
  lib/models/Teams.dart
  lib/utils/theme_config.dart
  lib/view/Chats/teamConversation.dart
  lib/view/homePage/home.dart
  lib/view/teams/teaminfo.dart
Labels: design, enhancement, frontend

#230 changed the home page
  lib/main.dart
  lib/view/mainapp.dart
  lib/view/teams/teaminfo.dart
  lib/widget/buildBottomNavigationBar.dart
Labels: design, frontend

#235 added chat background & added names in messages & enhanced custom message
  assets/chat background.png
  lib/view/Chats/conversation.dart
  lib/view/Chats/eventConversation.dart
  lib/view/Chats/teamConversation.dart
  lib/view/teams/teaminfo.dart
Labels: design, frontend

#239 enhanced challenge screen UI and added some drawer buttons
  lib/view/homePage/home.dart
  lib/view/profile/drawer/drawer.dart
  lib/view/profile/drawer/faq.dart
  lib/view/profile/drawer/moreInfo.dart
  lib/view/teams/challengeScreen.dart
Labels: design, enhancement, frontend

#244 added onboarding screens
  lib/main.dart
  lib/view/splash/onBoarding.dart
  lib/view/splash/splash.dart
  lib/view/views.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, frontend

#248 added username to profile pages
  lib/utils/theme_config.dart
  lib/view/Explore Events/addPost.dart
  lib/view/profile/drawer/drawer.dart
  lib/view/profile/drawer/faq.dart
  lib/view/profile/otherUserProfile.dart
  lib/view/profile/profilePage.dart
  lib/view/profile/schedule.dart
  lib/view/teams/challengeScreen.dart
  lib/view/teams/teamCategory.dart
Labels: design, enhancement, frontend

#251 onboarding completed
  assets/basketballGuy.png
  assets/chatting_illustration.png
  assets/notifications.png
  assets/post_online.png
  assets/real_life.png
  lib/view/auth/gauthPage.dart
  lib/view/splash/onBoarding.dart
  lib/view/splash/splash.dart
  lib/view/teams/teamsPage.dart
  lib/widget/googleOauth.dart
Labels: design, enhancement, frontend

#254 persistent darkmode added
  assets/googleicon.png
  lib/models/User.dart
  lib/utils/theme_config.dart
  lib/view/Explore Events/exploreEvents.dart
  lib/view/profile/profilePage.dart
  lib/widget/googleOauth.dart
  lib/widget/loader.dart
Labels: bug, frontend

#266 Bug fixes and logic enhanced
  lib/models/User.dart
  lib/services/EventService.dart
  lib/view/Chats/conversation.dart
  lib/view/Chats/messagePage.dart
  lib/view/profile/schedule.dart
Labels: backend, bug

#267 bugfix: darkmode persistency
  lib/utils/theme_config.dart
  lib/view/Chats/messagePage.dart
  lib/view/profile/otherUserProfile.dart
  lib/view/teams/teamCategory.dart
Labels: bug, frontend

#269 changed bottom nav bar design and bug fixed : onboarding screen issue with back button
  lib/main.dart
  lib/view/Chats/inviteFriends.dart
  lib/view/Explore Events/addPost.dart
  lib/view/mainapp.dart
  lib/view/splash/splash.dart
  lib/view/teamEventNotification.dart
  lib/view/teams/createTeam.dart
  lib/view/teams/teaminfo.dart
  lib/widget/buildBottomNavigationBar.dart
  lib/widget/googleOauth.dart
Labels: bug, design, enhancement, frontend

#273 enhanced team card UI
  lib/models/User.dart
  lib/view/profile/profilePage.dart
  lib/view/teams/teaminfo.dart
  lib/view/teams/teamsPage.dart
Labels: design, enhancement, frontend

#278 many UI Improvements
  lib/view/Chats/chatSchedule.dart
  lib/view/Chats/conversation.dart
  lib/view/Chats/eventConversation.dart
  lib/view/Chats/messagePage.dart
  lib/view/Chats/teamConversation.dart
  lib/view/Explore Events/addPost.dart
  lib/view/Explore Events/eventInfo.dart
  lib/view/Explore Events/specific_sport.dart
  lib/view/auth/forgotPassword.dart
  lib/view/profile/drawer/ImageCrop.dart
  lib/view/profile/drawer/editProfile.dart
  lib/view/profile/drawer/faq.dart
  lib/view/profile/drawer/moreInfo.dart
  lib/view/profile/drawer/testPage.dart
  lib/view/profile/otherUserProfile.dart
  lib/view/profile/profilePage.dart
  lib/view/teams/createTeam.dart
  lib/view/teams/teamCategory.dart
  lib/view/teams/teaminfo.dart
  lib/widget/buildTitle.dart
  lib/widget/customAnimatedContainer.dart
  lib/widget/customBackButton.dart
  lib/widget/widgets.dart
Labels: bug, design, frontend

#281 made the events info page and removed renderflex issues on explore events page
  android/app/src/main/AndroidManifest.xml
  assets/basketball-image.jpg
  assets/cricket-image.jpg
  assets/football-image.jpg
  assets/volleyball-image.jpg
  lib/view/Chats/eventConversation.dart
  lib/view/Explore Events/eventInfo.dart
  lib/view/Explore Events/exploreEvents.dart
  lib/widget/buildBottomNavigationBar.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, design, enhancement, frontend

#284 fixed renderflex issues in teams page
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/view/profile/drawer/editProfile.dart
  lib/view/teams/createTeam.dart
  lib/view/teams/teamsPage.dart
Labels: bug, enhancement, frontend
